name: Update README with Recent Activity
on:
  schedule:
    - cron: '*/30 * * * *'  # በየ30 ደቂቃ
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: Readme-Workflows/recent-activity@v2.4.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          COMMIT_MSG: "⚡ READMEን በቅርብ እንቅስቃሴ አዘምን"
          MAX_LINES: 5
